// Source: "Tabela de Preços - Momentus - Verão 2027" — section "MORMAII SPORTS"
// (the FITNESS / training catalog). Retail price = cost (US$) x RETAIL_MULTIPLIER.
// Format per line: CODE | DESCRIPTION | COST_USD

export const RETAIL_MULTIPLIER = 3.8;

const RAW = `
80574 GA|TOP FAIXA AD FEM MARY MORMAII C/ ALCAS ROLETE E ESTAMPA|3.57
80575 GA|MACAQUINHO AD FEM MARY MORMAII C/ EST|4.93
80576 GA|TOP REGATA AD FEM MARY MORMAII C/ EST|4.70
80577 GA|SHORTS AD FEM MALHA FURADINHA C/ SHORTS INTERNO MARY BLACK MORMAII C/ EST|6.37
80578 GA|CAMISETA CROPPED AD FEM M/M PENT MORMAII CARECA C/ EST|3.71
80579 GA|SHORTS AD FEM MARY MORMAII C/ EST|3.60
80580 GA|SHORTS AD FEM MARY MORMAII C/ EST|3.78
80582 GA|CAMISETA AD FEM M/M PENT MORMAII C/ EST|4.13
80584 GA|CALCA AD FEM LEGGING MARY MORMAII C/ EST|5.60
80586 GA|CALCA AD FEM LEGGING MARY MORMAII C/ BOLSO LATERAL E EST|7.35
80587 GA|SHORTS AD FEM MARY MORMAII C/ BOLSO LATERAL E EST|5.44
80588 GA|TOP AD FEM POWER COMFY MORMAII C/ TERMO|5.62
80589 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII COM TERMOCOLANTE|7.86
80590 GA|SHORTS AD FEM POWER COMFY MORMAII COM TERMOCOLANTE|5.72
80591 GA|TOP AD FEM POWER COMFY MORMAII C/ BOLSO E EST|5.58
80592 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII C/ EST|7.67
80593 GA|SHORTS AD FEM LEGGING POWER COMFY MORMAII C/ EST|5.21
80594 GA|CALCA AD FEM LEGGING FLARE POWER GLOSS MORMAII C/ BOLSO ENVELOPE E ESTAMPA|10.45
80595 GA|SHORTS AD FEM POWER GLOSS MORMAII C/ BOLSO ENVELOPE E ESTAMPA|6.14
80596 GA|TOP AD FEM POWER GLOSS MORMAII C/ ALCAS ROLETE E ESTAMPA|4.34
80597 GA|TOP AD FEM POWER GLOSS MORMAII C/ ALCA ROLOTE E ESTAMPA|6.20
80599 GA|VESTIDO COM SHORTS INTERNO AD FEM MARY MORMAII C/ REC E EST|7.94
80600 GA|BLUSA CROPPED CRISTAL MORMAII COM ESTAMPA|4.64
80601 GA|MACACAO AD FEM POWER GLOSS MORMAII C/ ALCA ROLOTE E EST|13.77
80602 GA|CALCA AD FEM LEGGING POWER GLOSS MORMAII C/ BOLSO ENVELOPE E ESTAMPA|9.16
80604 GA|TOP AD FEM POWER COMFY MORMAII C/ ALCA E TERMO|5.09
80605 GA|REGATA AD FEM COTTON MORMAII C/ TERMO|3.63
80606 GA|BODY AD FEM CRISTAL MORMAII C/ ALCAS E TERMOCOLANTE|5.02
80607 GA|SAIA AD FEM CRISTAL MORMAII C/ SHORTS SEP. ABERTURA E TERMOCOLANTE|6.75
80608 GA|TOP AD FEM MARY MORMAII C/ EST|4.59
80609 GA|TOP DUPLO AD FEM DRY MINI POINT E MARY MORMAII C/ ALCAS E ETIQ EMBORRACHADA|6.28
80610 GA|CROPPED AD FEM DRY MINI POINT MORMAII C/ EMBORRACHADO|4.18
80611 GA|TOP AD FEM MARY MORMAII C/ RECORTE DRY MINI POINT E ETIQ|7.02
80612 GA|SAIA SHORTS AD FEM DRY MINI POINT MORMAII C/ ETIQ EMBORRACHADA|9.43
80613 GA|CAMISETA AD FEM CRISTAL MORMAII C/ ABERTURA LATERAL E ESTAMPA|6.95
80614 GA|TOP AD FEM POWER COMFY MORMAII C/ ALCAS DUPLAS ROLOTE E ESTAMPA|6.03
80615 GA|TOP AD FEM POWER COMFY MORMAII C/ REC ELASTICO PERSONALIZADO E ESTAMPA|6.48
80616 GA|CALCA AD FEM LEGGING POWER CONFY MORMAII C/ REC E EST|10.25
80617 GA|REGATA AD FEM CRISTAL COM ABERTURA COSTAS E TERMO|4.53
80618 GA|BLUSA AD FEM CRISTAL MORMAII ML C/PUNHOS E TERMO|5.02
80619 GA|SHORTS AD FEM MADRID SUPLEX MORMAII C/ SHORTS INTERNO NEOPRENE E LASER|9.11
80620 GA|JAQUETA AD FEM MADRID MORMAII C/ ELASTICO PERSONALIZADO E LOGO EM LASER|13.27
80621 GA|SHORTS AD FEM TACTEL ASPEN C/ SHORTS INTERNO SUPLEX MORMAII C/ EST|6.19
80622 GA|TOP NADADOR AD FEM DEMICOMPRESSION MORMAII C/ REC E EST|10.33
80623 GA|CALCA AD FEM DEMICOMPRESSION MORMAII C/ BOLSOS E ESTAMPA|13.59
80624 GA|SHORTS AD FEM DEMICOMPRESSION MORMAII C/ BOLSO E ESTAMPA|8.89
80625 GA|TOP AD FEM DEMICOMPRESSION MORMAII C/ ALCA REGULADOR E EST|8.00
80626 GA|CAMISETA AD FEM CRISTAL MORMAII C/ ESTAMPA|6.14
80627 GA|SHORTS AD FEM CRISTAL C/ SHORTS INTERNO DEMICOMPRESSION MORMAII C/ EST|11.80
80628 GA|SHORTS AD FEM POWER COMFY MORMAII C/RECORTES E TERMO|7.63
80629 GA|CALCA AD FEM POWER COMFY MORMAII C/ RECORTES E TERMO|9.65
80630 GA|TOP AD FEM POWER COMFY MORMAII C/ ABERTURA COSTAS E TERMO|8.14
80631 GA|TOP AD FEM CIRRE POLIAMIDA COM ELASTANO MORMAII C/ ALCA TRAVETE E EST|7.66
80632 GA|TOP AD FEM CIRRE POLIAMIDA COM ELASTANO MORMAII C/ REC FILETE E EST|7.82
80633 GA|CALCA AD FEM LEGGING CIRRE POLIAMIDA COM ELASTANO MORMAII C/ REC FILETE E EST|16.63
80634 GA|MACACAO AD FEM MARY MORMAII C/ RECORTES ALCAS REGULADOR E EST|9.30
80635 GA|BODY AD FEM CRISTAL MORMAII C/ ALCAS ROLOTE E ESTAMPA|4.94
80637 GA|REGATA AD FEM MALHA COTTON MORMAII C/ EST|4.52
80638 GA|REGATA CROPPED AD FEM RIBANA CANELADA MORMAII C/ EST|3.00
80639 GA|CAMISA AD FEM RIBANA MORMAII GOLA POLO C/ BORDADO|5.94
80640 GA|REGATA AD FEM RIBANA CANELADA MORMAII C/ EST|3.67
80641 GA|REGATA AD FEM CROPPED MALHA COTTON MORMAII C/ EST|3.30
80642 GA|TOP AD FEM MARY MORMAII C/ ALCAS EST|4.88
80643 GA|CALCA AD FEM LEGGING MARY MORMAII C/ BOLSO ENVELOPE E ESTAMPA|6.42
80644 GA|REGATA AD FEM MALHA COTTON MORMAII C/ GOLA PEITILHO E EST|5.51
80645 GA|SHORTS AD FEM MARY MORMAII C/ BOLSO ENVELOPE E ESTAMPA|4.45
80646 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII C/ EST|6.75
80647 GA|TOP AD FEM POWER COMFY MORMAII C/ EST|5.20
80648 GA|SHORTS AD FEM POWER COMFY MORMAII C/ EST|4.41
80649 GA|CAMISETA AD FEM CRISTAL MORMAII C/ MANGA RAGLAN RECORTE E ESTAMPA|5.68
80650 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII C/ RECORTES BOLSO E EST|8.76
80651 GA|SHORTS AD FEM POWER COMFY MORMAII C/ BOLSO LATERAL E EST|6.25
80652 GA|TOP AD FEM POWER COMFY MORMAII C/ RECORTE FILETE ALCAS ROLOTE E ESTAMPA|5.39
80653 GA|TOP NADADOR AD FEM POWER COMFY MORMAII C/ ESTAMPA|5.80
80654 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII C/ COS TRANSPASSADO E EST|6.79
80655 GA|MACAQUINHO AD FEM POWER COMFY MORMAII C/ ALCA ROLOTE E EST|9.33
80656 GA|TOP FAIXA AD FEM POWER COMFY MORMAII C/ ALCAS ROLETE E ESTAMPA|3.94
80657 GA|BODY AD FEM CRISTAL MORMAII C/ EST E TERMO|6.71
80658 GA|SAIA SHORTS AD FEM DRY MALHA FURADINHA DRY E MARY MORMAII C/ EST|6.04
80659 GA|REGATA AD FEM MALHA FURADINHA MORMAII C/ EST|4.14
80660 GA|CAMISETA AD MASC HELANCA DRY MORMAII C/ EST|3.66
80661 GA|CAMISETA AD MASC M/M PENT MORMAII CARECA C/ EST|5.70
80662 GA|TOP REGATA AD FEM CROCO MARY MORMAII C/ ZIPER E ESTAMPA|7.66
80663 GA|SHORTS AD FEM CROCO MARY MORMAII C/ BOLSO LATERAL E EST|7.20
80664 GA|CALCA AD FEM LEGGING CROCO MARY MORMAII C/ BOLSO LATERAL E EST|9.21
80665 GA|CALCA AD FEM LEGGING POWER COMFY MORMAII C/ PEZINHO E EST|7.68
80666 GA|TOP REGATA AD FEM POWER COMFY MORMAII C/ ESTAMPA|6.39
80667 GA|SHORTS AD FEM POWER COMFY MORMAII C/ EST|4.52
80668 GA|REGATA AD FEM MALHA COTTON MORMAII C/ ABERTURA LAT E EST|4.74
80669 GA|VESTIDO AD FEM CRISTAL MORMAII C/ SHORTS SEP. E ESTAMPA|8.55
80670 GA|TOP AD FEM POWER COMFY MORMAII C/ ALCA ROLOTE E EST|4.61
80671 GA|SAIA SHORTS AD FEM CRISTAL MORMAII C/ PREGAS E EST|7.33
80672 GA|SAIA SHORTS AD FEM DRY AIR FLOW MORMAII C/ EST|6.72
80673 GA|SHORTS AD FEM DRY AIR FLOW MORMAII C/ EST|6.95
80681 GA|TOP REGATA AD FEM MARY MORMAII C/ EST FULL PRINT|6.66
80682 GA|CALCA AD FEM MARY MORMAII C/ EST FULL PRINT|9.27
80683 GA|SHORTS AD FEM MARY MORMAII C/ EST FULL PRINT|6.84
80684 GA|REGATA COM TOP AD FEM DRY AIR FLOW MORMAII C/ ALCA ROLOTE E EST|7.68
80685 GA|TOP AD FEM POWER COMFY MORMAII C/ EST FULL PRINT|6.27
80686 GA|CALCA AD FEM POWER COMFY MORMAII C/ BOLSO E EST FULL PRINT|11.08
80687 GA|SHORTS AD FEM POWER COMFY MORMAII C/ BOLSO E EST FULL PRINT|7.02
80688 GA|CAMISETA AD MASC M/M PENT MORMAII CARECA C/ EST|3.95
80689 GA|CAMISETA AD MASC CRISTAL MORMAII C/ REC E EST|6.40
80690 GA|CAMISETA AD MASC CRISTAL MORMAII C/ RECORTES DRY AIR FLOW E EST|7.31
80691 GA|CAMISETA AD MASC M/M PENT MORMAII CARECA C/ EST|5.22
80692 GA|CAMISETA AD MASC CRISTAL MORMAII ML C/ EST|6.00
80693 GA|CAMISETA AD MASC MALHA FURADINHA DRY MORMAII C/ MANGA RAGLAN DETALHE GOLA E EST|4.42
80694 GA|CAMISETA AD MASC CRISTAL MORMAII C/ TERMO|5.54
80695 GA|CAMISETA AD MASC DRY AIR FLOW MORMAII C/ EST|5.47
80696 GA|BERMUDA AD MASC CRISTAL MORMAII C/ SHORTS INTERNO E RECORTE E TERMO|10.14
80697 GA|BERMUDA AD MASC CRISTAL MORMAII C/ ELASTICO PERSONALIZADO E ETIQ|8.39
80698 GA|BERMUDA AD MASC MALHA FURADINHA DRY C/ SHORTS INTERNO SUPLEX MORMAII C/ EST|8.61
80699 GA|MACHAO AD MASC MALHA FURADINHA DRY MORMAII CARECA C/ EST|3.14
80700 GA|MACHAO AD MASC DRY AIR FLOW MORMAII C/ EST|5.45
80701 GA|SHORTS AD FEM CRISTAL MORMAII C/ SHORTS INTERNO E EST|7.11
80702 GA|CAMISETA AD MASC HELANCA DRY MORMAII CARECA C/ EST|3.41
80703 GA|FAIXA DE CABELO MARY MORMAII C/ ESTAMPA|1.74
80827 GA|TOP AD FEM DRY AIR FLOW MORMAII C/ ALCA ROLOTE E EST|3.92
`;

export type Gender = "Mujer" | "Hombre" | "Unisex";

export type Product = {
  code: string;
  imgCode: string;
  rawName: string;
  name: string;
  category: string;
  gender: Gender;
  cost: number;
  retail: number;
  sizes: string[];
};

const APPAREL_SIZES = ["PP", "P", "M", "G", "GG", "XG"];
const ONE_SIZE = ["Único"];

function categoryOf(desc: string): string {
  const d = desc.toUpperCase();
  if (d.startsWith("FAIXA DE CABELO")) return "Accesorios";
  if (d.startsWith("TOP")) return "Tops";
  if (d.startsWith("MACAQUINHO") || d.startsWith("MACACAO")) return "Enterizos";
  if (d.startsWith("SHORTS")) return "Shorts";
  if (d.startsWith("CALCA")) return d.includes("LEGGING") ? "Calzas / Leggings" : "Pantalones";
  if (d.startsWith("REGATA")) return "Musculosas";
  if (d.startsWith("MACHAO")) return "Musculosas";
  if (d.startsWith("CAMISETA")) return "Remeras";
  if (d.startsWith("CAMISA")) return "Camisas";
  if (d.startsWith("BERMUDA")) return "Bermudas";
  if (d.startsWith("BLUSA")) return "Blusas";
  if (d.startsWith("BODY")) return "Bodies";
  if (d.startsWith("SAIA")) return "Polleras";
  if (d.startsWith("VESTIDO")) return "Vestidos";
  if (d.startsWith("JAQUETA")) return "Camperas";
  if (d.startsWith("CROPPED")) return "Cropped";
  return "Otros";
}

function genderOf(desc: string): Gender {
  const d = ` ${desc.toUpperCase()} `;
  if (d.includes(" FEM ")) return "Mujer";
  if (d.includes(" MASC ")) return "Hombre";
  return "Unisex";
}

// Light cleanup so respondents see a readable name instead of factory shorthand.
function prettyName(desc: string): string {
  let s = ` ${desc} `;
  s = s.replace(/ MORMAII /g, " ");
  s = s.replace(/ \bAD\b /g, " ");
  s = s.replace(/ \bFEM\b /g, " ");
  s = s.replace(/ \bMASC\b /g, " ");
  s = s.replace(/ \bM\/M\b /g, " manga corta ");
  s = s.replace(/ \bML\b /g, " manga larga ");
  s = s.replace(/ \bPENT\b /g, " ");
  s = s.replace(/ \bC\//g, " con ");
  s = s.replace(/ \bS\//g, " sin ");
  s = s.replace(/ \bEST\b/g, " estampa");
  s = s.replace(/ \bESTAMPA\b/g, " estampa");
  s = s.replace(/ \bREC\b/g, " recorte");
  s = s.replace(/ \bETIQ\b/g, " etiqueta");
  s = s.replace(/ \bTERMO\b/g, " termocolante");
  s = s.replace(/\s+E\s+estampa/gi, " y estampa");
  s = s.replace(/\s+/g, " ").trim();
  // Title-case words, keep short connectors lowercase.
  const lower = new Set(["con", "sin", "y", "e", "de", "da", "do"]);
  s = s
    .toLowerCase()
    .split(" ")
    .map((w, i) => (i > 0 && lower.has(w) ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ");
  return s;
}

function parse(): Product[] {
  return RAW.trim()
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [code, desc, costStr] = line.split("|");
      const cost = parseFloat(costStr);
      const retail = Math.round(cost * RETAIL_MULTIPLIER * 100) / 100;
      const category = categoryOf(desc);
      const trimmedCode = code.trim();
      const imgCode = (trimmedCode.match(/\d+/)?.[0] || trimmedCode).trim();
      return {
        code: trimmedCode,
        imgCode,
        rawName: desc.trim(),
        name: prettyName(desc.trim()),
        category,
        gender: genderOf(desc),
        cost,
        retail,
        sizes: category === "Accesorios" ? ONE_SIZE : APPAREL_SIZES,
      };
    });
}

export const PRODUCTS: Product[] = parse();

export const CATEGORIES: string[] = Array.from(
  new Set(PRODUCTS.map((p) => p.category)),
).sort();

export const GENDERS: Gender[] = ["Mujer", "Hombre", "Unisex"];

export function productByCode(code: string): Product | undefined {
  return PRODUCTS.find((p) => p.code === code);
}
